hydra:
  job_logging:
#    formatters:
#      simple:
#        format: '[]'
    root:
      handlers: [file, console]  # logging to file only.
  run:
    #dir: logs/${dataset}
    dir: logs/${dataset}

dataset: cifar10
data_dir: data
classifier_name: resnet18 # or resnet34, resnet50
width: 16
n_split: 3  # for bias-variance estimation design


n_classes: 10

inference: False  # False for training, True for inference.

# training parameters
n_epochs: 100
n_batch_train: 128
n_batch_test: 200

optimizer: sgd
lr: 0.1
momentum: 0.9
weight_decay: 0.0005
schedule: [50, 75]  # Decrease learning rate at these epochs.
gamma: 0.1  # LR is multiplied by gamma on schedule.

seed: 1234
n_gpu: 1
device: cpu
